// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package org.tensorflow.framework.config

/** Options passed to the graph optimizer
  *
  * @param doCommonSubexpressionElimination
  *   If true, optimize the graph using common subexpression elimination.
  *   Note: the optimization Level L1 will override this setting to true. So in
  *   order to disable common subexpression elimination the opt_level has to be
  *   set to L0.
  * @param doConstantFolding
  *   If true, perform constant folding optimization on the graph.
  *   Note: the optimization Level L1 will override this setting to true. So in
  *   order to disable constant folding the opt_level has to be set to L0.
  * @param maxFoldedConstantInBytes
  *   Constant folding optimization replaces tensors whose values can be
  *   predetermined, with constant nodes. To avoid inserting too large constants,
  *   the size of each constant created can be limited. If this value is zero, a
  *   default limit of 10 MiB will be applied. If constant folding optimization
  *   is disabled, this value is ignored.
  * @param doFunctionInlining
  *   If true, perform function inlining on the graph.
  * @param optLevel
  *   Overall optimization level. The actual optimizations applied will be the
  *   logical OR of the flags that this level implies and any flags already set.
  * @param cpuGlobalJit
  *   CPU code will be autoclustered only if global_jit_level &gt;= ON_1 and either:
  *    - this flag is true, or
  *    - TF_XLA_FLAGS contains --tf_xla_cpu_global_jit=true.
  */
@SerialVersionUID(0L)
final case class OptimizerOptions(
    doCommonSubexpressionElimination: _root_.scala.Boolean = false,
    doConstantFolding: _root_.scala.Boolean = false,
    maxFoldedConstantInBytes: _root_.scala.Long = 0L,
    doFunctionInlining: _root_.scala.Boolean = false,
    optLevel: org.tensorflow.framework.config.OptimizerOptions.Level = org.tensorflow.framework.config.OptimizerOptions.Level.L1,
    globalJitLevel: org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.DEFAULT,
    cpuGlobalJit: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[OptimizerOptions] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = doCommonSubexpressionElimination
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
        }
      };
      
      {
        val __value = doConstantFolding
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(2, __value)
        }
      };
      
      {
        val __value = maxFoldedConstantInBytes
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(6, __value)
        }
      };
      
      {
        val __value = doFunctionInlining
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(4, __value)
        }
      };
      
      {
        val __value = optLevel.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
        }
      };
      
      {
        val __value = globalJitLevel.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(5, __value)
        }
      };
      
      {
        val __value = cpuGlobalJit
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(7, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = doCommonSubexpressionElimination
        if (__v != false) {
          _output__.writeBool(1, __v)
        }
      };
      {
        val __v = doConstantFolding
        if (__v != false) {
          _output__.writeBool(2, __v)
        }
      };
      {
        val __v = optLevel.value
        if (__v != 0) {
          _output__.writeEnum(3, __v)
        }
      };
      {
        val __v = doFunctionInlining
        if (__v != false) {
          _output__.writeBool(4, __v)
        }
      };
      {
        val __v = globalJitLevel.value
        if (__v != 0) {
          _output__.writeEnum(5, __v)
        }
      };
      {
        val __v = maxFoldedConstantInBytes
        if (__v != 0L) {
          _output__.writeInt64(6, __v)
        }
      };
      {
        val __v = cpuGlobalJit
        if (__v != false) {
          _output__.writeBool(7, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withDoCommonSubexpressionElimination(__v: _root_.scala.Boolean): OptimizerOptions = copy(doCommonSubexpressionElimination = __v)
    def withDoConstantFolding(__v: _root_.scala.Boolean): OptimizerOptions = copy(doConstantFolding = __v)
    def withMaxFoldedConstantInBytes(__v: _root_.scala.Long): OptimizerOptions = copy(maxFoldedConstantInBytes = __v)
    def withDoFunctionInlining(__v: _root_.scala.Boolean): OptimizerOptions = copy(doFunctionInlining = __v)
    def withOptLevel(__v: org.tensorflow.framework.config.OptimizerOptions.Level): OptimizerOptions = copy(optLevel = __v)
    def withGlobalJitLevel(__v: org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel): OptimizerOptions = copy(globalJitLevel = __v)
    def withCpuGlobalJit(__v: _root_.scala.Boolean): OptimizerOptions = copy(cpuGlobalJit = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = doCommonSubexpressionElimination
          if (__t != false) __t else null
        }
        case 2 => {
          val __t = doConstantFolding
          if (__t != false) __t else null
        }
        case 6 => {
          val __t = maxFoldedConstantInBytes
          if (__t != 0L) __t else null
        }
        case 4 => {
          val __t = doFunctionInlining
          if (__t != false) __t else null
        }
        case 3 => {
          val __t = optLevel.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 5 => {
          val __t = globalJitLevel.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 7 => {
          val __t = cpuGlobalJit
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PBoolean(doCommonSubexpressionElimination)
        case 2 => _root_.scalapb.descriptors.PBoolean(doConstantFolding)
        case 6 => _root_.scalapb.descriptors.PLong(maxFoldedConstantInBytes)
        case 4 => _root_.scalapb.descriptors.PBoolean(doFunctionInlining)
        case 3 => _root_.scalapb.descriptors.PEnum(optLevel.scalaValueDescriptor)
        case 5 => _root_.scalapb.descriptors.PEnum(globalJitLevel.scalaValueDescriptor)
        case 7 => _root_.scalapb.descriptors.PBoolean(cpuGlobalJit)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: org.tensorflow.framework.config.OptimizerOptions.type = org.tensorflow.framework.config.OptimizerOptions
    // @@protoc_insertion_point(GeneratedMessage[tensorboard.OptimizerOptions])
}

object OptimizerOptions extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.config.OptimizerOptions] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.config.OptimizerOptions] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.config.OptimizerOptions = {
    var __doCommonSubexpressionElimination: _root_.scala.Boolean = false
    var __doConstantFolding: _root_.scala.Boolean = false
    var __maxFoldedConstantInBytes: _root_.scala.Long = 0L
    var __doFunctionInlining: _root_.scala.Boolean = false
    var __optLevel: org.tensorflow.framework.config.OptimizerOptions.Level = org.tensorflow.framework.config.OptimizerOptions.Level.L1
    var __globalJitLevel: org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.DEFAULT
    var __cpuGlobalJit: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __doCommonSubexpressionElimination = _input__.readBool()
        case 16 =>
          __doConstantFolding = _input__.readBool()
        case 48 =>
          __maxFoldedConstantInBytes = _input__.readInt64()
        case 32 =>
          __doFunctionInlining = _input__.readBool()
        case 24 =>
          __optLevel = org.tensorflow.framework.config.OptimizerOptions.Level.fromValue(_input__.readEnum())
        case 40 =>
          __globalJitLevel = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.fromValue(_input__.readEnum())
        case 56 =>
          __cpuGlobalJit = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.config.OptimizerOptions(
        doCommonSubexpressionElimination = __doCommonSubexpressionElimination,
        doConstantFolding = __doConstantFolding,
        maxFoldedConstantInBytes = __maxFoldedConstantInBytes,
        doFunctionInlining = __doFunctionInlining,
        optLevel = __optLevel,
        globalJitLevel = __globalJitLevel,
        cpuGlobalJit = __cpuGlobalJit,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.config.OptimizerOptions] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.config.OptimizerOptions(
        doCommonSubexpressionElimination = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        doConstantFolding = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        maxFoldedConstantInBytes = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        doFunctionInlining = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        optLevel = org.tensorflow.framework.config.OptimizerOptions.Level.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(org.tensorflow.framework.config.OptimizerOptions.Level.L1.scalaValueDescriptor).number),
        globalJitLevel = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.DEFAULT.scalaValueDescriptor).number),
        cpuGlobalJit = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.config.ConfigProtoCompanion.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.config.ConfigProtoCompanion.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?]= throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?]= {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => org.tensorflow.framework.config.OptimizerOptions.Level
      case 5 => org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel
    }
  }
  lazy val defaultInstance = org.tensorflow.framework.config.OptimizerOptions(
    doCommonSubexpressionElimination = false,
    doConstantFolding = false,
    maxFoldedConstantInBytes = 0L,
    doFunctionInlining = false,
    optLevel = org.tensorflow.framework.config.OptimizerOptions.Level.L1,
    globalJitLevel = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.DEFAULT,
    cpuGlobalJit = false
  )
  /** Optimization level
    */
  sealed abstract class Level(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = org.tensorflow.framework.config.OptimizerOptions.Level
    type RecognizedType = org.tensorflow.framework.config.OptimizerOptions.Level.Recognized
    def isL1: _root_.scala.Boolean = false
    def isL0: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[Level] = org.tensorflow.framework.config.OptimizerOptions.Level
    final def asRecognized: _root_.scala.Option[org.tensorflow.framework.config.OptimizerOptions.Level.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.tensorflow.framework.config.OptimizerOptions.Level.Recognized])
  }
  
  object Level extends _root_.scalapb.GeneratedEnumCompanion[Level] {
    sealed trait Recognized extends Level
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[Level] = this
    
    /** L1 is the default level.
      * Optimization performed at L1 :
      * 1. Common subexpression elimination
      * 2. Constant folding
      */
    @SerialVersionUID(0L)
    case object L1 extends Level(0) with Level.Recognized {
      val index = 0
      val name = "L1"
      override def isL1: _root_.scala.Boolean = true
    }
    
    /** No optimizations
      */
    @SerialVersionUID(0L)
    case object L0 extends Level(-1) with Level.Recognized {
      val index = 1
      val name = "L0"
      override def isL0: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends Level(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(L1, L0)
    def fromValue(__value: _root_.scala.Int): Level = __value match {
      case -1 => L0
      case 0 => L1
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.tensorflow.framework.config.OptimizerOptions.javaDescriptor.getEnumTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.tensorflow.framework.config.OptimizerOptions.scalaDescriptor.enums(0)
  }
  /** Control the use of the compiler/jit.  Experimental.
    */
  sealed abstract class GlobalJitLevel(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
    type EnumType = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel
    type RecognizedType = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.Recognized
    def isDefault: _root_.scala.Boolean = false
    def isOff: _root_.scala.Boolean = false
    def isOn1: _root_.scala.Boolean = false
    def isOn2: _root_.scala.Boolean = false
    def companion: _root_.scalapb.GeneratedEnumCompanion[GlobalJitLevel] = org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel
    final def asRecognized: _root_.scala.Option[org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel.Recognized])
  }
  
  object GlobalJitLevel extends _root_.scalapb.GeneratedEnumCompanion[GlobalJitLevel] {
    sealed trait Recognized extends GlobalJitLevel
    implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[GlobalJitLevel] = this
    
    /** Default setting ("off" now, but later expected to be "on")
      */
    @SerialVersionUID(0L)
    case object DEFAULT extends GlobalJitLevel(0) with GlobalJitLevel.Recognized {
      val index = 0
      val name = "DEFAULT"
      override def isDefault: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object OFF extends GlobalJitLevel(-1) with GlobalJitLevel.Recognized {
      val index = 1
      val name = "OFF"
      override def isOff: _root_.scala.Boolean = true
    }
    
    /** The following settings turn on compilation, with higher values being
      * more aggressive.  Higher values may reduce opportunities for parallelism
      * and may use more memory.  (At present, there is no distinction, but this
      * is expected to change.)
      */
    @SerialVersionUID(0L)
    case object ON_1 extends GlobalJitLevel(1) with GlobalJitLevel.Recognized {
      val index = 2
      val name = "ON_1"
      override def isOn1: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    case object ON_2 extends GlobalJitLevel(2) with GlobalJitLevel.Recognized {
      val index = 3
      val name = "ON_2"
      override def isOn2: _root_.scala.Boolean = true
    }
    
    @SerialVersionUID(0L)
    final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends GlobalJitLevel(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
    lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(DEFAULT, OFF, ON_1, ON_2)
    def fromValue(__value: _root_.scala.Int): GlobalJitLevel = __value match {
      case -1 => OFF
      case 0 => DEFAULT
      case 1 => ON_1
      case 2 => ON_2
      case __other => Unrecognized(__other)
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = org.tensorflow.framework.config.OptimizerOptions.javaDescriptor.getEnumTypes().get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = org.tensorflow.framework.config.OptimizerOptions.scalaDescriptor.enums(1)
  }
  implicit class OptimizerOptionsLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.config.OptimizerOptions]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.config.OptimizerOptions](_l) {
    def doCommonSubexpressionElimination: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.doCommonSubexpressionElimination)((c_, f_) => c_.copy(doCommonSubexpressionElimination = f_))
    def doConstantFolding: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.doConstantFolding)((c_, f_) => c_.copy(doConstantFolding = f_))
    def maxFoldedConstantInBytes: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.maxFoldedConstantInBytes)((c_, f_) => c_.copy(maxFoldedConstantInBytes = f_))
    def doFunctionInlining: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.doFunctionInlining)((c_, f_) => c_.copy(doFunctionInlining = f_))
    def optLevel: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.config.OptimizerOptions.Level] = field(_.optLevel)((c_, f_) => c_.copy(optLevel = f_))
    def globalJitLevel: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel] = field(_.globalJitLevel)((c_, f_) => c_.copy(globalJitLevel = f_))
    def cpuGlobalJit: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.cpuGlobalJit)((c_, f_) => c_.copy(cpuGlobalJit = f_))
  }
  final val DO_COMMON_SUBEXPRESSION_ELIMINATION_FIELD_NUMBER = 1
  final val DO_CONSTANT_FOLDING_FIELD_NUMBER = 2
  final val MAX_FOLDED_CONSTANT_IN_BYTES_FIELD_NUMBER = 6
  final val DO_FUNCTION_INLINING_FIELD_NUMBER = 4
  final val OPT_LEVEL_FIELD_NUMBER = 3
  final val GLOBAL_JIT_LEVEL_FIELD_NUMBER = 5
  final val CPU_GLOBAL_JIT_FIELD_NUMBER = 7
  def of(
    doCommonSubexpressionElimination: _root_.scala.Boolean,
    doConstantFolding: _root_.scala.Boolean,
    maxFoldedConstantInBytes: _root_.scala.Long,
    doFunctionInlining: _root_.scala.Boolean,
    optLevel: org.tensorflow.framework.config.OptimizerOptions.Level,
    globalJitLevel: org.tensorflow.framework.config.OptimizerOptions.GlobalJitLevel,
    cpuGlobalJit: _root_.scala.Boolean
  ): _root_.org.tensorflow.framework.config.OptimizerOptions = _root_.org.tensorflow.framework.config.OptimizerOptions(
    doCommonSubexpressionElimination,
    doConstantFolding,
    maxFoldedConstantInBytes,
    doFunctionInlining,
    optLevel,
    globalJitLevel,
    cpuGlobalJit
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorboard.OptimizerOptions])
}
