// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package org.tensorflow.framework.step_stats

@SerialVersionUID(0L)
final case class StepStats(
    devStats: _root_.scala.Seq[org.tensorflow.framework.step_stats.DeviceStepStats] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[StepStats] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      devStats.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      devStats.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearDevStats = copy(devStats = _root_.scala.Seq.empty)
    def addDevStats(__vs: org.tensorflow.framework.step_stats.DeviceStepStats *): StepStats = addAllDevStats(__vs)
    def addAllDevStats(__vs: Iterable[org.tensorflow.framework.step_stats.DeviceStepStats]): StepStats = copy(devStats = devStats ++ __vs)
    def withDevStats(__v: _root_.scala.Seq[org.tensorflow.framework.step_stats.DeviceStepStats]): StepStats = copy(devStats = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => devStats
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(devStats.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: org.tensorflow.framework.step_stats.StepStats.type = org.tensorflow.framework.step_stats.StepStats
    // @@protoc_insertion_point(GeneratedMessage[tensorboard.StepStats])
}

object StepStats extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.step_stats.StepStats] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.step_stats.StepStats] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.step_stats.StepStats = {
    val __devStats: _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.step_stats.DeviceStepStats] = new _root_.scala.collection.immutable.VectorBuilder[org.tensorflow.framework.step_stats.DeviceStepStats]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __devStats += _root_.scalapb.LiteParser.readMessage[org.tensorflow.framework.step_stats.DeviceStepStats](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.step_stats.StepStats(
        devStats = __devStats.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.step_stats.StepStats] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.step_stats.StepStats(
        devStats = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[org.tensorflow.framework.step_stats.DeviceStepStats]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.step_stats.StepStatsProto.javaDescriptor.getMessageTypes().get(6)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.step_stats.StepStatsProto.scalaDescriptor.messages(6)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?]= {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?]= null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = org.tensorflow.framework.step_stats.DeviceStepStats
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?]= throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.framework.step_stats.StepStats(
    devStats = _root_.scala.Seq.empty
  )
  implicit class StepStatsLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.step_stats.StepStats]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.step_stats.StepStats](_l) {
    def devStats: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.tensorflow.framework.step_stats.DeviceStepStats]] = field(_.devStats)((c_, f_) => c_.copy(devStats = f_))
  }
  final val DEV_STATS_FIELD_NUMBER = 1
  def of(
    devStats: _root_.scala.Seq[org.tensorflow.framework.step_stats.DeviceStepStats]
  ): _root_.org.tensorflow.framework.step_stats.StepStats = _root_.org.tensorflow.framework.step_stats.StepStats(
    devStats
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorboard.StepStats])
}
