// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package tensorboard.saved_object_graph

/** @param saveFunction
  *   Node ids of concrete functions for saving and loading from a checkpoint.
  *   These functions save and restore directly from tensors.
  */
@SerialVersionUID(0L)
final case class SaveableObject(
    saveFunction: _root_.scala.Int = 0,
    restoreFunction: _root_.scala.Int = 0,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SaveableObject] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = saveFunction
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, __value)
        }
      };
      
      {
        val __value = restoreFunction
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = saveFunction
        if (__v != 0) {
          _output__.writeInt32(2, __v)
        }
      };
      {
        val __v = restoreFunction
        if (__v != 0) {
          _output__.writeInt32(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withSaveFunction(__v: _root_.scala.Int): SaveableObject = copy(saveFunction = __v)
    def withRestoreFunction(__v: _root_.scala.Int): SaveableObject = copy(restoreFunction = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 2 => {
          val __t = saveFunction
          if (__t != 0) __t else null
        }
        case 3 => {
          val __t = restoreFunction
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 2 => _root_.scalapb.descriptors.PInt(saveFunction)
        case 3 => _root_.scalapb.descriptors.PInt(restoreFunction)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: tensorboard.saved_object_graph.SaveableObject.type = tensorboard.saved_object_graph.SaveableObject
    // @@protoc_insertion_point(GeneratedMessage[tensorboard.SaveableObject])
}

object SaveableObject extends scalapb.GeneratedMessageCompanion[tensorboard.saved_object_graph.SaveableObject] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[tensorboard.saved_object_graph.SaveableObject] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): tensorboard.saved_object_graph.SaveableObject = {
    var __saveFunction: _root_.scala.Int = 0
    var __restoreFunction: _root_.scala.Int = 0
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 16 =>
          __saveFunction = _input__.readInt32()
        case 24 =>
          __restoreFunction = _input__.readInt32()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    tensorboard.saved_object_graph.SaveableObject(
        saveFunction = __saveFunction,
        restoreFunction = __restoreFunction,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[tensorboard.saved_object_graph.SaveableObject] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      tensorboard.saved_object_graph.SaveableObject(
        saveFunction = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        restoreFunction = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = tensorboard.saved_object_graph.SavedObjectGraphProto.javaDescriptor.getMessageTypes().get(12)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = tensorboard.saved_object_graph.SavedObjectGraphProto.scalaDescriptor.messages(12)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = tensorboard.saved_object_graph.SaveableObject(
    saveFunction = 0,
    restoreFunction = 0
  )
  implicit class SaveableObjectLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, tensorboard.saved_object_graph.SaveableObject]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, tensorboard.saved_object_graph.SaveableObject](_l) {
    def saveFunction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.saveFunction)((c_, f_) => c_.copy(saveFunction = f_))
    def restoreFunction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.restoreFunction)((c_, f_) => c_.copy(restoreFunction = f_))
  }
  final val SAVE_FUNCTION_FIELD_NUMBER = 2
  final val RESTORE_FUNCTION_FIELD_NUMBER = 3
  def of(
    saveFunction: _root_.scala.Int,
    restoreFunction: _root_.scala.Int
  ): _root_.tensorboard.saved_object_graph.SaveableObject = _root_.tensorboard.saved_object_graph.SaveableObject(
    saveFunction,
    restoreFunction
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorboard.SaveableObject])
}
