// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package tensorboard.saved_object_graph

import tensorflow.framework.versions
import tensorflow.framework.versions.VersionDef

/** A SavedUserObject is an object (in the object-oriented language of the
  * TensorFlow program) of some user- or framework-defined class other than
  * those handled specifically by the other kinds of SavedObjects.
  *
  * This object cannot be evaluated as a tensor, and therefore cannot be bound
  * to an input of a function.
  *
  * @param identifier
  *   Corresponds to a registration of the type to use in the loading program.
  * @param version
  *   Version information from the producer of this SavedUserObject.
  * @param metadata
  *   Metadata for deserializing this object.
  *  
  *   Deprecated! At the time of deprecation, Keras was the only user of this
  *   field, and its saving and loading code will be updated shortly.
  *   Please save your application-specific metadata to a separate file.
  */
@SerialVersionUID(0L)
final case class SavedUserObject(
                                  identifier: _root_.scala.Predef.String = "",
                                  version: _root_.scala.Option[VersionDef] = _root_.scala.None,
                                  @scala.deprecated(message="Marked as deprecated in proto file", "") metadata: _root_.scala.Predef.String = "",
                                  unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SavedUserObject] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = identifier
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      if (version.isDefined) {
        val __value = version.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = metadata
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = identifier
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      version.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = metadata
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withIdentifier(__v: _root_.scala.Predef.String): SavedUserObject = copy(identifier = __v)
    def getVersion: VersionDef = version.getOrElse(VersionDef.defaultInstance)
    def clearVersion: SavedUserObject = copy(version = _root_.scala.None)
    def withVersion(__v: VersionDef): SavedUserObject = copy(version = Option(__v))
    def withMetadata(__v: _root_.scala.Predef.String): SavedUserObject = copy(metadata = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = identifier
          if (__t != "") __t else null
        }
        case 2 => version.orNull
        case 3 => {
          val __t = metadata
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(identifier)
        case 2 => version.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => _root_.scalapb.descriptors.PString(metadata)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: tensorboard.saved_object_graph.SavedUserObject.type = tensorboard.saved_object_graph.SavedUserObject
    // @@protoc_insertion_point(GeneratedMessage[tensorboard.SavedUserObject])
}

object SavedUserObject extends scalapb.GeneratedMessageCompanion[tensorboard.saved_object_graph.SavedUserObject] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[tensorboard.saved_object_graph.SavedUserObject] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): tensorboard.saved_object_graph.SavedUserObject = {
    var __identifier: _root_.scala.Predef.String = ""
    var __version: _root_.scala.Option[VersionDef] = _root_.scala.None
    var __metadata: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __identifier = _input__.readStringRequireUtf8()
        case 18 =>
          __version = _root_.scala.Option(__version.fold(_root_.scalapb.LiteParser.readMessage[VersionDef](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __metadata = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    tensorboard.saved_object_graph.SavedUserObject(
        identifier = __identifier,
        version = __version,
        metadata = __metadata,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[tensorboard.saved_object_graph.SavedUserObject] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      tensorboard.saved_object_graph.SavedUserObject(
        identifier = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        version = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[VersionDef]]),
        metadata = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = tensorboard.saved_object_graph.SavedObjectGraphProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = tensorboard.saved_object_graph.SavedObjectGraphProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = versions.VersionDef
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = tensorboard.saved_object_graph.SavedUserObject(
    identifier = "",
    version = _root_.scala.None,
    metadata = ""
  )
  implicit class SavedUserObjectLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, tensorboard.saved_object_graph.SavedUserObject]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, tensorboard.saved_object_graph.SavedUserObject](_l) {
    def identifier: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.identifier)((c_, f_) => c_.copy(identifier = f_))
    def version: _root_.scalapb.lenses.Lens[UpperPB, VersionDef] = field(_.getVersion)((c_, f_) => c_.copy(version = _root_.scala.Option(f_)))
    def optionalVersion: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[VersionDef]] = field(_.version)((c_, f_) => c_.copy(version = f_))
    def metadata: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.metadata)((c_, f_) => c_.copy(metadata = f_))
  }
  final val IDENTIFIER_FIELD_NUMBER = 1
  final val VERSION_FIELD_NUMBER = 2
  final val METADATA_FIELD_NUMBER = 3
  def of(
          identifier: _root_.scala.Predef.String,
          version: _root_.scala.Option[VersionDef],
          metadata: _root_.scala.Predef.String
  ): _root_.tensorboard.saved_object_graph.SavedUserObject = _root_.tensorboard.saved_object_graph.SavedUserObject(
    identifier,
    version,
    metadata
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorboard.SavedUserObject])
}
