// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package tensorboard.coordination_config

object CoordinationConfigProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      tensorboard.coordination_config.CoordinatedJob,
      tensorboard.coordination_config.CoordinationServiceConfig
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjJ0ZW5zb3Jib2FyZC9jb21wYXQvcHJvdG8vY29vcmRpbmF0aW9uX2NvbmZpZy5wcm90bxILdGVuc29yYm9hcmQiWwoOQ29vc
  mRpbmF0ZWRKb2ISHQoEbmFtZRgBIAEoCUIJ4j8GEgRuYW1lUgRuYW1lEioKCW51bV90YXNrcxgCIAEoBUIN4j8KEghudW1UYXNrc
  1IIbnVtVGFza3MilwkKGUNvb3JkaW5hdGlvblNlcnZpY2VDb25maWcSMwoMc2VydmljZV90eXBlGAEgASgJQhDiPw0SC3NlcnZpY
  2VUeXBlUgtzZXJ2aWNlVHlwZRI5Cg5zZXJ2aWNlX2xlYWRlchgCIAEoCUIS4j8PEg1zZXJ2aWNlTGVhZGVyUg1zZXJ2aWNlTGVhZ
  GVyEkYKE2VuYWJsZV9oZWFsdGhfY2hlY2sYAyABKAhCFuI/ExIRZW5hYmxlSGVhbHRoQ2hlY2tSEWVuYWJsZUhlYWx0aENoZWNrE
  mMKHmNsdXN0ZXJfcmVnaXN0ZXJfdGltZW91dF9pbl9tcxgEIAEoA0If4j8cEhpjbHVzdGVyUmVnaXN0ZXJUaW1lb3V0SW5Nc1IaY
  2x1c3RlclJlZ2lzdGVyVGltZW91dEluTXMSYgodY2x1c3Rlcl9yZWdpc3Rlcl93aXRoX2JhcnJpZXIYDiABKAhCH+I/HBIaY2x1c
  3RlclJlZ2lzdGVyV2l0aEJhcnJpZXJSGmNsdXN0ZXJSZWdpc3RlcldpdGhCYXJyaWVyElAKF2hlYXJ0YmVhdF90aW1lb3V0X2luX
  21zGAUgASgDQhniPxYSFGhlYXJ0YmVhdFRpbWVvdXRJbk1zUhRoZWFydGJlYXRUaW1lb3V0SW5NcxJmChRjb29yZGluYXRlZF9qb
  2JfbGlzdBgKIAMoCzIbLnRlbnNvcmJvYXJkLkNvb3JkaW5hdGVkSm9iQhfiPxQSEmNvb3JkaW5hdGVkSm9iTGlzdFISY29vcmRpb
  mF0ZWRKb2JMaXN0EmMKHnNodXRkb3duX2JhcnJpZXJfdGltZW91dF9pbl9tcxgHIAEoA0If4j8cEhpzaHV0ZG93bkJhcnJpZXJUa
  W1lb3V0SW5Nc1Iac2h1dGRvd25CYXJyaWVyVGltZW91dEluTXMScQoiYWdlbnRfZGVzdHJ1Y3Rpb25fd2l0aG91dF9zaHV0ZG93b
  hgIIAEoCEIk4j8hEh9hZ2VudERlc3RydWN0aW9uV2l0aG91dFNodXRkb3duUh9hZ2VudERlc3RydWN0aW9uV2l0aG91dFNodXRkb
  3duEj8KEHJlY292ZXJhYmxlX2pvYnMYCSADKAlCFOI/ERIPcmVjb3ZlcmFibGVKb2JzUg9yZWNvdmVyYWJsZUpvYnMSbwoiYWxsb
  3dfbmV3X2luY2FybmF0aW9uX3RvX3JlY29ubmVjdBgLIAEoCEIj4j8gEh5hbGxvd05ld0luY2FybmF0aW9uVG9SZWNvbm5lY3RSH
  mFsbG93TmV3SW5jYXJuYXRpb25Ub1JlY29ubmVjdBI2Cg1mb3JjZV9kaXNhYmxlGAwgASgIQhHiPw4SDGZvcmNlRGlzYWJsZVIMZ
  m9yY2VEaXNhYmxlEncKJnBvbGxfZm9yX2Vycm9yX2Zyb21fc2VydmljZV9hdF9zdGFydHVwGA0gASgIQiXiPyISIHBvbGxGb3JFc
  nJvckZyb21TZXJ2aWNlQXRTdGFydHVwUiBwb2xsRm9yRXJyb3JGcm9tU2VydmljZUF0U3RhcnR1cEoECAYQB0JXWlVnaXRodWIuY
  29tL3RlbnNvcmZsb3cvdGVuc29yZmxvdy90ZW5zb3JmbG93L2dvL2NvcmUvcHJvdG9idWYvZm9yX2NvcmVfcHJvdG9zX2dvX3Byb
  3RvYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}