// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package org.tensorflow.framework.function

/** RegisteredGradient stores a gradient function that is registered in the
  * gradients library and used in the ops of a function in the function library.
  * Unlike GradientDef, these gradients are identified by op type, and not
  * directly linked to any function.
  *
  * @param gradientFunc
  *   The gradient function's name.
  * @param registeredOpType
  *   The gradient function's registered op type.
  */
@SerialVersionUID(0L)
final case class RegisteredGradient(
    gradientFunc: _root_.scala.Predef.String = "",
    registeredOpType: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[RegisteredGradient] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = gradientFunc
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = registeredOpType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = gradientFunc
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = registeredOpType
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withGradientFunc(__v: _root_.scala.Predef.String): RegisteredGradient = copy(gradientFunc = __v)
    def withRegisteredOpType(__v: _root_.scala.Predef.String): RegisteredGradient = copy(registeredOpType = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = gradientFunc
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = registeredOpType
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(gradientFunc)
        case 2 => _root_.scalapb.descriptors.PString(registeredOpType)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: org.tensorflow.framework.function.RegisteredGradient.type = org.tensorflow.framework.function.RegisteredGradient
    // @@protoc_insertion_point(GeneratedMessage[tensorboard.RegisteredGradient])
}

object RegisteredGradient extends scalapb.GeneratedMessageCompanion[org.tensorflow.framework.function.RegisteredGradient] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.tensorflow.framework.function.RegisteredGradient] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.tensorflow.framework.function.RegisteredGradient = {
    var __gradientFunc: _root_.scala.Predef.String = ""
    var __registeredOpType: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __gradientFunc = _input__.readStringRequireUtf8()
        case 18 =>
          __registeredOpType = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.tensorflow.framework.function.RegisteredGradient(
        gradientFunc = __gradientFunc,
        registeredOpType = __registeredOpType,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.tensorflow.framework.function.RegisteredGradient] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.tensorflow.framework.function.RegisteredGradient(
        gradientFunc = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        registeredOpType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.tensorflow.framework.function.FunctionProto.javaDescriptor.getMessageTypes().get(3)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.tensorflow.framework.function.FunctionProto.scalaDescriptor.messages(3)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?]= throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?]= throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.tensorflow.framework.function.RegisteredGradient(
    gradientFunc = "",
    registeredOpType = ""
  )
  implicit class RegisteredGradientLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.tensorflow.framework.function.RegisteredGradient]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.tensorflow.framework.function.RegisteredGradient](_l) {
    def gradientFunc: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.gradientFunc)((c_, f_) => c_.copy(gradientFunc = f_))
    def registeredOpType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.registeredOpType)((c_, f_) => c_.copy(registeredOpType = f_))
  }
  final val GRADIENT_FUNC_FIELD_NUMBER = 1
  final val REGISTERED_OP_TYPE_FIELD_NUMBER = 2
  def of(
    gradientFunc: _root_.scala.Predef.String,
    registeredOpType: _root_.scala.Predef.String
  ): _root_.org.tensorflow.framework.function.RegisteredGradient = _root_.org.tensorflow.framework.function.RegisteredGradient(
    gradientFunc,
    registeredOpType
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[tensorboard.RegisteredGradient])
}
